# Generated by Django 3.0.6 on 2020-06-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('author', models.CharField(blank=True, max_length=125)),
                ('image', models.ImageField(blank=True, upload_to='books/images')),
                ('image_url', models.URLField(blank=True)),
                ('descriptions', models.TextField(blank=True)),
                ('download', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
