# Generated by Django 3.0.6 on 2020-06-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1, unique=True),
            preserve_default=False,
        ),
    ]
