# Generated by Django 3.0.7 on 2020-06-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200607_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='iframe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, editable=False, unique=True),
        ),
    ]
