# Generated by Django 3.0.7 on 2020-06-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whois', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterField(
            model_name='persion',
            name='persion_img',
            field=models.ImageField(unique=True, upload_to='persions/images'),
        ),
    ]
